/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'dgtl-tenants': DgtlTenant;
    'cms-users': CmsUser;
    websites: Website;
    pages: Page;
    posts: Post;
    media: Media;
    navigation: Navigation;
    'site-settings': SiteSetting;
    'content-requests': ContentRequest;
    'activity-events': ActivityEvent;
    'revalidation-deliveries': RevalidationDelivery;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'dgtl-tenants': DgtlTenantsSelect<false> | DgtlTenantsSelect<true>;
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    websites: WebsitesSelect<false> | WebsitesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'content-requests': ContentRequestsSelect<false> | ContentRequestsSelect<true>;
    'activity-events': ActivityEventsSelect<false> | ActivityEventsSelect<true>;
    'revalidation-deliveries': RevalidationDeliveriesSelect<false> | RevalidationDeliveriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dgtl-tenants".
 */
export interface DgtlTenant {
  id: number;
  key: string;
  displayName: string;
  status: 'draft' | 'active' | 'suspended' | 'archived';
  primaryContactName?: string | null;
  primaryContactEmail?: string | null;
  branding?: {
    logo?: (number | null) | Media;
    primaryColor?: string | null;
  };
  notes?: string | null;
  activatedAt?: string | null;
  suspendedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  website: number | Website;
  alt?: string | null;
  decorative?: boolean | null;
  caption?: string | null;
  credit?: string | null;
  classification: 'public' | 'private-admin';
  checksum?: string | null;
  scanStatus: 'pending' | 'clean' | 'rejected';
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites".
 */
export interface Website {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  key: string;
  displayName: string;
  status: 'draft' | 'active' | 'maintenance' | 'suspended';
  domain: string;
  previewDomain?: string | null;
  frontendKey: string;
  contentModelVersion: number;
  revalidationUrl?: string | null;
  /**
   * Reference name from CMS_REVALIDATION_SECRETS; never paste the secret itself here.
   */
  revalidationSecretRef?: string | null;
  mediaBaseUrl?: string | null;
  homepage?: (number | null) | Page;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  /**
   * Uses the website assigned to the currently selected client.
   */
  website: number | Website;
  title: string;
  slug: string;
  template: 'standard' | 'landing' | 'contact' | 'service';
  /**
   * Choose an approved font treatment for this page. This changes the Client 01 page without allowing unsafe custom CSS.
   */
  typography?: {
    fontFamily?: ('brand' | 'sans' | 'serif') | null;
  };
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        text?: string | null;
        image?: (number | null) | Media;
        video?: (number | null) | Media;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        activeServiceLinkLabel?: string | null;
        cardLinkLabel?: string | null;
        scrollPrompt?: string | null;
        desktopServicesLabel?: string | null;
        mobileServicesLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        heading?: string | null;
        /**
         * Select and order the Service pages shown in the DGTL360 service wheel and reel.
         */
        servicePages: (number | Page)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceIndex';
      }
    | {
        anchor?: string | null;
        kicker: string;
        heading: string;
        lead: string;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        capabilities?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        link: {
          label: string;
          url: string;
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'companyOverview';
      }
    | {
        anchor?: string | null;
        kicker: string;
        heading: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statement';
      }
    | {
        anchor?: string | null;
        kicker: string;
        heading: string;
        instruction: string;
        portraitImage?: (number | null) | Media;
        profileImage?: (number | null) | Media;
        members?:
          | {
              number: string;
              role: string;
              description: string;
              portraitPosition?: string | null;
              profilePosition?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamShowcase';
      }
    | {
        wordmark: string;
        ariaLabel: string;
        alphabets?:
          | {
              characters: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'identityField';
      }
    | {
        order: number;
        label: string;
        cardHeadline: string;
        preview: string;
        summary: string;
        detailDescription: string;
        tagline: string;
        accent: string;
        image?: (number | null) | Media;
        imagePosition?: string | null;
        sections?:
          | {
              title: string;
              body?: string | null;
              items?:
                | {
                    title: string;
                    description?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceDetail';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading: string;
        text: string;
        image?: (number | null) | Media;
        alignment: 'image-left' | 'image-right';
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageText';
      }
    | {
        heading: string;
        text?: string | null;
        link: {
          label: string;
          url: string;
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        heading?: string | null;
        cards?:
          | {
              title: string;
              text: string;
              link: {
                label: string;
                url: string;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        images: (number | Media)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading?: string | null;
        email?: string | null;
        phone?: string | null;
        address?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactDetails';
      }
    | {
        heading?: string | null;
        items?:
          | {
              label: string;
              image: number | Media;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoCloud';
      }
    | {
        size?: ('small' | 'medium' | 'large') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'spacer';
      }
  )[];
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  showInNavigation?: boolean | null;
  publishedAt?: string | null;
  archivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  displayName: string;
  accountType: 'company' | 'client';
  companyRoles?: 'company-super-admin'[] | null;
  status: 'invited' | 'active' | 'suspended';
  lastLoginAt?: string | null;
  invitedBy?: (number | null) | CmsUser;
  passwordChangedAt?: string | null;
  tenants?:
    | {
        tenant: number | DgtlTenant;
        roles: 'client-admin'[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  /**
   * Uses the website assigned to the currently selected client.
   */
  website: number | Website;
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        text?: string | null;
        image?: (number | null) | Media;
        video?: (number | null) | Media;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        activeServiceLinkLabel?: string | null;
        cardLinkLabel?: string | null;
        scrollPrompt?: string | null;
        desktopServicesLabel?: string | null;
        mobileServicesLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading: string;
        text: string;
        image?: (number | null) | Media;
        alignment: 'image-left' | 'image-right';
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageText';
      }
    | {
        heading: string;
        text?: string | null;
        link: {
          label: string;
          url: string;
          newTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        heading?: string | null;
        cards?:
          | {
              title: string;
              text: string;
              link: {
                label: string;
                url: string;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        images: (number | Media)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading?: string | null;
        email?: string | null;
        phone?: string | null;
        address?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactDetails';
      }
    | {
        heading?: string | null;
        items?:
          | {
              label: string;
              image: number | Media;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoCloud';
      }
    | {
        size?: ('small' | 'medium' | 'large') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'spacer';
      }
  )[];
  categories?: string[] | null;
  authorDisplayName?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  publishedAt?: string | null;
  archivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  website: number | Website;
  location: 'header' | 'footer';
  items?:
    | {
        label: string;
        page?: (number | null) | Page;
        externalURL?: string | null;
        newTab?: boolean | null;
        enabled?: boolean | null;
        order?: number | null;
        children?:
          | {
              label: string;
              page?: (number | null) | Page;
              externalURL?: string | null;
              newTab?: boolean | null;
              enabled?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  website: number | Website;
  displayName: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSEO?: {
    title?: string | null;
    description?: string | null;
    socialImage?: (number | null) | Media;
  };
  brandContent?: {
    locationLabel?: string | null;
    footerEyebrow?: string | null;
    /**
     * Use a new line or | to control line breaks.
     */
    footerHeading?: string | null;
    footerDescription?: string | null;
    legalLocation?: string | null;
    backToTopLabel?: string | null;
  };
  enquiryContent?: {
    homeKicker?: string | null;
    serviceKicker?: string | null;
    serviceHeading?: string | null;
    serviceText?: string | null;
    addressLabel?: string | null;
    nameLabel?: string | null;
    emailLabel?: string | null;
    companyLabel?: string | null;
    phoneLabel?: string | null;
    messageLabel?: string | null;
    submitLabel?: string | null;
    sendingLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
  };
  serviceContent?: {
    breadcrumbLabel?: string | null;
    reelKicker?: string | null;
    reelHeading?: string | null;
    reelInstruction?: string | null;
    backLabel?: string | null;
  };
  footerText?: string | null;
  analyticsReference?: string | null;
  locale?: string | null;
  timezone?: string | null;
  maintenanceEnabled?: boolean | null;
  maintenanceMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-requests".
 */
export interface ContentRequest {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  website: number | Website;
  requester: number | CmsUser;
  title: string;
  description: string;
  targetPage?: (number | null) | Page;
  priority: 'low' | 'normal' | 'high' | 'urgent';
  attachments?: (number | Media)[] | null;
  assignedTo?: (number | null) | CmsUser;
  status: 'submitted' | 'reviewing' | 'needs-information' | 'in-progress' | 'client-review' | 'completed' | 'cancelled';
  comments?:
    | {
        author: number | CmsUser;
        message: string;
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  internalNotes?: string | null;
  requestedDueDate?: string | null;
  completedAt?: string | null;
  resultingPage?: (number | null) | Page;
  resultingVersionID?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-events".
 */
export interface ActivityEvent {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  website?: (number | null) | Website;
  actorID: string;
  actorDisplayName: string;
  actorType: 'company' | 'client' | 'service';
  action: string;
  targetCollection: string;
  targetID: string;
  summary: string;
  requestID?: string | null;
  outcome: 'succeeded' | 'failed' | 'denied';
  timestamp: string;
  changedFields?: string[] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revalidation-deliveries".
 */
export interface RevalidationDelivery {
  id: number;
  tenant?: (number | null) | DgtlTenant;
  website: number | Website;
  sourceCollection: string;
  sourceDocumentID: string;
  sourceVersionID?: string | null;
  eventType: string;
  cacheTags: string[];
  cachePaths: string[];
  idempotencyKey: string;
  state: 'pending' | 'delivering' | 'succeeded' | 'retrying' | 'failed';
  attemptCount: number;
  nextAttemptAt?: string | null;
  lastSafeError?: string | null;
  responseStatus?: number | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'dgtl-tenants';
        value: number | DgtlTenant;
      } | null)
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'websites';
        value: number | Website;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'content-requests';
        value: number | ContentRequest;
      } | null)
    | ({
        relationTo: 'activity-events';
        value: number | ActivityEvent;
      } | null)
    | ({
        relationTo: 'revalidation-deliveries';
        value: number | RevalidationDelivery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dgtl-tenants_select".
 */
export interface DgtlTenantsSelect<T extends boolean = true> {
  key?: T;
  displayName?: T;
  status?: T;
  primaryContactName?: T;
  primaryContactEmail?: T;
  branding?:
    | T
    | {
        logo?: T;
        primaryColor?: T;
      };
  notes?: T;
  activatedAt?: T;
  suspendedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  displayName?: T;
  accountType?: T;
  companyRoles?: T;
  status?: T;
  lastLoginAt?: T;
  invitedBy?: T;
  passwordChangedAt?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "websites_select".
 */
export interface WebsitesSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  displayName?: T;
  status?: T;
  domain?: T;
  previewDomain?: T;
  frontendKey?: T;
  contentModelVersion?: T;
  revalidationUrl?: T;
  revalidationSecretRef?: T;
  mediaBaseUrl?: T;
  homepage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  title?: T;
  slug?: T;
  template?: T;
  typography?:
    | T
    | {
        fontFamily?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              image?: T;
              video?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    id?: T;
                  };
              activeServiceLinkLabel?: T;
              cardLinkLabel?: T;
              scrollPrompt?: T;
              desktopServicesLabel?: T;
              mobileServicesLabel?: T;
              id?: T;
              blockName?: T;
            };
        serviceIndex?:
          | T
          | {
              heading?: T;
              servicePages?: T;
              id?: T;
              blockName?: T;
            };
        companyOverview?:
          | T
          | {
              anchor?: T;
              kicker?: T;
              heading?: T;
              lead?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              capabilities?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              anchor?: T;
              kicker?: T;
              heading?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        teamShowcase?:
          | T
          | {
              anchor?: T;
              kicker?: T;
              heading?: T;
              instruction?: T;
              portraitImage?: T;
              profileImage?: T;
              members?:
                | T
                | {
                    number?: T;
                    role?: T;
                    description?: T;
                    portraitPosition?: T;
                    profilePosition?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        identityField?:
          | T
          | {
              wordmark?: T;
              ariaLabel?: T;
              alphabets?:
                | T
                | {
                    characters?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceDetail?:
          | T
          | {
              order?: T;
              label?: T;
              cardHeadline?: T;
              preview?: T;
              summary?: T;
              detailDescription?: T;
              tagline?: T;
              accent?: T;
              image?: T;
              imagePosition?: T;
              sections?:
                | T
                | {
                    title?: T;
                    body?: T;
                    items?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              text?: T;
              image?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactDetails?:
          | T
          | {
              heading?: T;
              email?: T;
              phone?: T;
              address?: T;
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    image?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  showInNavigation?: T;
  publishedAt?: T;
  archivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              image?: T;
              video?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    id?: T;
                  };
              activeServiceLinkLabel?: T;
              cardLinkLabel?: T;
              scrollPrompt?: T;
              desktopServicesLabel?: T;
              mobileServicesLabel?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              text?: T;
              image?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactDetails?:
          | T
          | {
              heading?: T;
              email?: T;
              phone?: T;
              address?: T;
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    image?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  categories?: T;
  authorDisplayName?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  publishedAt?: T;
  archivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  classification?: T;
  checksum?: T;
  scanStatus?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        page?: T;
        externalURL?: T;
        newTab?: T;
        enabled?: T;
        order?: T;
        children?:
          | T
          | {
              label?: T;
              page?: T;
              externalURL?: T;
              newTab?: T;
              enabled?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  displayName?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
      };
  brandContent?:
    | T
    | {
        locationLabel?: T;
        footerEyebrow?: T;
        footerHeading?: T;
        footerDescription?: T;
        legalLocation?: T;
        backToTopLabel?: T;
      };
  enquiryContent?:
    | T
    | {
        homeKicker?: T;
        serviceKicker?: T;
        serviceHeading?: T;
        serviceText?: T;
        addressLabel?: T;
        nameLabel?: T;
        emailLabel?: T;
        companyLabel?: T;
        phoneLabel?: T;
        messageLabel?: T;
        submitLabel?: T;
        sendingLabel?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  serviceContent?:
    | T
    | {
        breadcrumbLabel?: T;
        reelKicker?: T;
        reelHeading?: T;
        reelInstruction?: T;
        backLabel?: T;
      };
  footerText?: T;
  analyticsReference?: T;
  locale?: T;
  timezone?: T;
  maintenanceEnabled?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-requests_select".
 */
export interface ContentRequestsSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  requester?: T;
  title?: T;
  description?: T;
  targetPage?: T;
  priority?: T;
  attachments?: T;
  assignedTo?: T;
  status?: T;
  comments?:
    | T
    | {
        author?: T;
        message?: T;
        createdAt?: T;
        id?: T;
      };
  internalNotes?: T;
  requestedDueDate?: T;
  completedAt?: T;
  resultingPage?: T;
  resultingVersionID?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-events_select".
 */
export interface ActivityEventsSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  actorID?: T;
  actorDisplayName?: T;
  actorType?: T;
  action?: T;
  targetCollection?: T;
  targetID?: T;
  summary?: T;
  requestID?: T;
  outcome?: T;
  timestamp?: T;
  changedFields?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revalidation-deliveries_select".
 */
export interface RevalidationDeliveriesSelect<T extends boolean = true> {
  tenant?: T;
  website?: T;
  sourceCollection?: T;
  sourceDocumentID?: T;
  sourceVersionID?: T;
  eventType?: T;
  cacheTags?: T;
  cachePaths?: T;
  idempotencyKey?: T;
  state?: T;
  attemptCount?: T;
  nextAttemptAt?: T;
  lastSafeError?: T;
  responseStatus?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}