export const dgtl360Assets = {
  heroVideo: { alt: 'Abstract mycelial transport animation', file: 'video/mycelial-transport.mp4' },
  teamPortraits: { alt: '', decorative: true, file: 'reference/team-collective.png' },
  teamProfiles: { alt: 'DGTL 360 team member editorial profile study', file: 'reference/team-profile.png' },
}

export const dgtl360Settings = {
  brandContent: {
    backToTopLabel: 'BACK TO TOP ↑',
    footerDescription: 'Brand, content, product, growth and the systems underneath—one accountable Colombo crew.',
    footerEyebrow: 'HAVE A PROBLEM WORTH SOLVING?',
    footerHeading: 'Let’s make the|next thing work.',
    legalLocation: 'COLOMBO, SRI LANKA',
    locationLabel: 'COLOMBO + ANYWHERE',
  },
  contact: {
    address: 'Mode Residence\n3 Beach Rd,\nDehiwala-Mount Lavinia',
    email: 'info@dgtl.lk',
    phone: '+94 11 000 0000',
  },
  defaultSEO: {
    description: 'One Colombo crew connecting brand, production, product, growth, digital systems, experiences and agentic AI.',
    title: 'DGTL 360',
  },
  displayName: 'DGTL 360',
  enquiryContent: {
    addressLabel: 'OUR ADDRESS',
    companyLabel: 'COMPANY',
    emailLabel: 'YOUR EMAIL ADDRESS *',
    errorMessage: 'We could not send your enquiry. Please try again or email info@dgtl.lk.',
    homeKicker: 'START AN ENQUIRY',
    messageLabel: 'YOUR MESSAGE *',
    nameLabel: 'YOUR NAME *',
    phoneLabel: 'PHONE',
    sendingLabel: 'SENDING…',
    serviceHeading: 'Let’s make your next move clear.',
    serviceKicker: 'CONTACT US',
    serviceText: 'Tell us what you are building, what feels stuck, or where you need traction. We’ll route the right DGTL 360 crew and the next useful step.',
    submitLabel: 'SEND ENQUIRY',
    successMessage: 'Thank you. Your enquiry has been sent.',
  },
  footerText: '© 2026 DGTL 360',
  serviceContent: {
    backLabel: '← BACK TO ALL SERVICES',
    breadcrumbLabel: '← SERVICES',
    reelHeading: 'Explore every service',
    reelInstruction: 'HOVER TO HOLD · SELECT A FRAME',
    reelKicker: 'DGTL 360 / SERVICE REEL',
  },
}

export const dgtl360HomeBlocks = {
  companyOverview: {
    anchor: 'who-we-are',
    blockType: 'companyOverview' as const,
    capabilities: [
      { label: 'Production' },
      { label: 'Brand & strategy' },
      { label: 'Web development' },
      { label: 'App development' },
      { label: 'Digital services' },
      { label: 'Events & experiences' },
      { label: 'Agentic AI' },
    ],
    heading: 'WHO\nWE ARE',
    kicker: 'INTEGRATED BUSINESS SOLUTIONS',
    lead: 'We are a like-minded collective built around shared thinking, open process and a better standard of problem-solving—for Sri Lanka and the wider world.',
    link: { label: 'BUILD A BETTER SOLUTION ↗', newTab: false, url: '/#enquiry' },
    paragraphs: [
      { text: 'Our arsenal is deliberately broad, but our realm is digital. We work across production, brand and strategy, web and app development, digital services, events and experiences, and agentic AI—assembling the right disciplines around every brief.' },
      { text: 'How we deliver is never fixed. We combine agentic models with experienced makers and technical advisors at every stage. The result is technology that strengthens human judgement and solutions built to move organisations and personal pursuits forward.' },
    ],
  },
  identityField: {
    alphabets: [
      { characters: 'අකගතනමයරල' },
      { characters: 'தமிழ்மொழி' },
      { characters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' },
      { characters: 'अआइकगचतभम' },
      { characters: 'ابتثجحخدذر' },
      { characters: 'ΑΒΓΔΘΛΣΩ' },
      { characters: '0123456789{}[]<>' },
    ],
    ariaLabel: 'DGTL logo with multilingual alphabet rain',
    blockType: 'identityField' as const,
    wordmark: 'DGTL',
  },
  statement: {
    anchor: 'our-attitude',
    blockType: 'statement' as const,
    heading: 'Sharp thinking,\nwarm humans,\nvery little agency\ntheatre.',
    kicker: 'OUR ATTITUDE',
    text: 'We ask the awkward question early, keep humans in charge and make the system earn its complexity. No loku scene.',
  },
  teamShowcase: {
    anchor: 'team',
    blockType: 'teamShowcase' as const,
    heading: 'The people\nmaking it\nhappen',
    instruction: 'Select any portrait to open their story.',
    kicker: 'DGTL 360 / THE CREW',
    members: [
      { description: 'Creates the positioning, priorities and decision path that align the crew before execution begins.', number: '01', portraitPosition: '8% 30%', profilePosition: '8% 30%', role: 'Strategy & Planning' },
      { description: 'Turns the useful problem into a distinctive idea and keeps every expression connected to it.', number: '02', portraitPosition: '28% 28%', profilePosition: '28% 28%', role: 'Creative Direction' },
      { description: 'Brings sound, image, motion and the operational details together from first take to delivery.', number: '03', portraitPosition: '51% 27%', profilePosition: '51% 27%', role: 'Production' },
      { description: 'Builds identities that remain coherent across people, platforms, campaigns and everyday use.', number: '04', portraitPosition: '75% 27%', profilePosition: '75% 27%', role: 'Brand Systems' },
      { description: 'Makes complex digital journeys feel clear, useful and resilient for the people using them.', number: '05', portraitPosition: '12% 65%', profilePosition: '12% 65%', role: 'Product Design' },
      { description: 'Builds maintainable platforms and integrations that survive real traffic and real operations.', number: '06', portraitPosition: '35% 63%', profilePosition: '35% 63%', role: 'Engineering' },
      { description: 'Connects creative work to measurable audience behaviour and keeps improving the learning loop.', number: '07', portraitPosition: '58% 62%', profilePosition: '58% 62%', role: 'Growth' },
      { description: 'Shapes the room, run sheet and production details around what people should feel and remember.', number: '08', portraitPosition: '82% 60%', profilePosition: '82% 60%', role: 'Experience' },
      { description: 'Keeps ownership, timing and delivery visible across a brief with several moving parts.', number: '09', portraitPosition: '25% 90%', profilePosition: '25% 90%', role: 'Operations' },
      { description: 'Introduces practical automation with visible controls, auditability and humans still accountable.', number: '10', portraitPosition: '55% 88%', profilePosition: '55% 88%', role: 'Agentic Systems' },
    ],
  },
}

export const dgtl360Services = [
  {
    accent: '#ff5c35',
    cardHeadline: 'Hear it first. See it through.',
    detailDescription: 'Production covers everything created in sound and colour. On the audio side, that includes original music, jingles, voiceovers and podcast production. Through visual, it’s TVCs, music videos, digital ads, corporate films, branded content, live productions and photography. This is all shaped through creative development before a frame is shot. Once it’s captured, post-production brings it together with motion graphics, animation, VFX, colour grading and AI-assisted content work.',
    image: 'services/production-v01.webp',
    imagePosition: '50% 50%',
    label: 'Production',
    order: 1,
    preview: 'Sound + Vision',
    sections: [
      { body: 'Everything sound: original song production and mastering, catchy brand jingles, IVR phone recordings, multi-language voiceovers, and complete podcast recording and editing.', title: 'Audio Production' },
      { body: 'Everything filmed: TV commercials, music videos, social media ads, company videos, brand stories, live event streams, and script-to-concept development.', title: 'Video Production' },
      { body: 'Everything shot: ad campaign imagery, e-commerce product photos, lifestyle visual shoots, and live event coverage.', title: 'Photography' },
      { body: 'Everything edited: 2D motion graphics, 3D animation, visual effects (VFX), video editing, cinematic color grading, and AI-powered content generation.', title: 'Motion & Post' },
    ],
    slug: 'production',
    summary: 'We build every production as one connected piece—sound, image and edit developed together, not stitched together after the fact. Composition, filming, photography and post-production stay tied to the same creative idea, from first take to final delivery.',
    tagline: 'Sound + Vision',
  },
  {
    accent: '#2350ff',
    cardHeadline: 'Find the idea. Build the system.',
    detailDescription: 'Branding & Strategy is where a business becomes its own unique brand. Starting with positioning, we find the right idea that makes your brand genuinely different. We build that into an identity through logo design, brand systems and artwork creation. We also connect it to a go-to-market plan covering trade marketing and business 0–1 foundations, so naming, messaging and launch all stay tied to the same strategic idea.',
    image: 'services/brand-strategy-v01.webp',
    imagePosition: '50% 50%',
    label: 'Branding & Strategy',
    order: 2,
    preview: 'Identity + System',
    sections: [
      { body: 'Positioning, target audience, brand purpose, values and messaging.', title: 'Brand Strategy' },
      { body: 'Logo, colour palette, typography and visual direction.', title: 'Brand Identity' },
      { body: 'Developing creative concepts, campaign ideas and visual content.', title: 'Creative Development' },
      { body: 'Big ideas, campaign concepts and communication.', title: 'Campaign Strategy' },
      { body: 'Business cards, presentations, packaging, menus, brochures, etc.', title: 'Brand Collateral' },
      { body: 'POSM, retail campaigns, in-store communication and activations.', title: 'Trade Marketing' },
      { body: 'Taking an idea from concept to launch, including brand, strategy and initial marketing setup.', title: 'Business 0–1 Solutions' },
    ],
    slug: 'brand-strategy',
    summary: 'Found the idea? Let’s build it into a distinctive identity. Positioning, naming, design and go-to-market decisions stay connected together.',
    tagline: 'Identity + System',
  },
  {
    accent: '#ff2d9a',
    cardHeadline: 'Digital Marketing',
    detailDescription: 'Digital Marketing covers how your brand shows up online, how well it performs and what happens once it’s live. That means digital and social media strategy, content creation across audio, video and graphics, day-to-day platform handling, targeted social and Google advertising, influencer partnerships, website design and development, and SEO—all working toward the same purpose.',
    image: 'services/social-growth-v01.webp',
    imagePosition: '50% 50%',
    label: 'Digital Marketing',
    order: 3,
    preview: 'Digital Marketing',
    sections: [
      { body: 'No guesswork, just a clear plan! We build smart digital strategies that help your brand reach the right people and grow online.', title: 'Digital Marketing Strategy' },
      { body: 'Good social media doesn’t happen by accident! A solid strategy keeps your brand moving, your content fresh and relevant, and your audience interested.', title: 'Social Media Strategy' },
      { body: 'There’s a LOT of content out there. So how do you get people to stop scrolling and notice yours? That’s where we come in, turning your ideas into eye-catching content that sparks curiosity, tells your story, and keeps your brand in all the right places.', title: 'Content Creation' },
      { body: 'You focus on your business, we’ll handle the socials! From planning and posting to engaging with your audience, we keep your platforms active, relevant, and on trend.', title: 'Social Media Platform Handling' },
      { body: 'It’s not just about putting money behind a post! We use your ad budget strategically, creating targeted campaigns that reach the right audience and drive real results. From awareness to leads and conversions, every ad spend counts.', title: 'Social Media Advertising' },
      { body: 'Smart targeting, the right placements, and campaigns built around what your brand wants to achieve, not just more clicks.', title: 'Google Advertising' },
      { body: 'Good brands deserve the right voices! We connect you with the right creators and build smart influencer campaigns. From the first conversation to the final post, we make sure everything comes together just right.', title: 'Influencer Marketing' },
      { body: 'Your website is your digital home. Let’s make it a good one! We create modern, user-friendly websites that look great and work even better.', title: 'Website Design & Development' },
      { body: 'Getting found shouldn’t be left to luck! From keywords and content to website performance, we focus on what helps search engines understand your brand and reach the right people. Building your visibility naturally, one search at a time.', title: 'Search Engine Optimization' },
    ],
    slug: 'digital-marketing',
    summary: 'Digital Marketing.',
    tagline: 'Digital Marketing',
  },
  {
    accent: '#ff9f1c',
    cardHeadline: 'Built to work. Built to last.',
    detailDescription: 'Web Development covers the systems a business actually runs on. This is not just the site customers see, but full-stack development handled front to back, CMS solutions for easy ongoing content control, and CRM and workflow integration that keeps customer systems and business processes moving in sync.',
    image: 'services/web-platforms-v01.webp',
    imagePosition: '50% 50%',
    label: 'Web Development',
    order: 4,
    preview: 'Build + Manage',
    sections: [
      { body: 'From the first click to the backend logic behind it, we build websites and apps that work seamlessly, end to end, so nothing falls through the cracks.', title: 'Full Stack Development' },
      { body: 'Your content, your control. We build easy-to-manage systems so you can update your site anytime, without waiting on a developer.', title: 'CMS Solutions' },
      { body: 'Less chasing, more closing. We set up smart systems that track your customers and automate the busywork, so your team can focus on what matters.', title: 'CRM & Workflows' },
    ],
    slug: 'web-platforms',
    summary: 'We develop the systems your business runs on, not just the site your customers see. Full-stack builds, CMS platforms and CRM workflows are designed together, so what’s under the hood holds up as well as what’s on the surface.',
    tagline: 'Build + Manage',
  },
  {
    accent: '#ff6247',
    cardHeadline: 'One idea. Every platform.',
    detailDescription: 'App Development covers building and running a product end to end. Agile development augmented with bespoke AI tools, native iOS and Android builds plus progressive web apps for reaching every platform, and ongoing DevOps support keep everything running smoothly long after launch.',
    image: 'services/apps-product-v01.webp',
    imagePosition: '50% 50%',
    label: 'App Development',
    order: 5,
    preview: 'Build + Operate',
    sections: [
      { body: 'Built in sprints, not guesswork. We move fast, adapt quickly, and keep you in the loop every step of the way.', title: 'Agile Development' },
      { body: 'One idea, every device. We build native apps that feel right at home on iPhone and Android alike.', title: 'iOS & Android Development' },
      { body: 'All the feel of an app, none of the download. Fast, reliable, and works even when the connection doesn’t.', title: 'Progressive Web Apps (PWA)' },
      { body: 'The engine behind the scenes. We keep your systems deploying smoothly, scaling safely, and running without the 3am surprises.', title: 'DevOps Augmentation' },
    ],
    slug: 'apps-product',
    summary: 'We take an app from its initial sprint to the first screen it is intended to run on. Agile development, native builds and DevOps support stay connected end-to-end, so your product ships fast, runs smoothly and keeps working long after first use.',
    tagline: 'Build + Operate',
  },
  {
    accent: '#0a7f5a',
    cardHeadline: 'Every touchpoint. One system.',
    detailDescription: 'Digital Services covers the operational systems behind customer experiences. That includes POS systems for smooth, reliable transactions and customer service call centre solutions that keep support responsive at any volume. HRM solutions simplify people management from onboarding onward, while enterprise solutions are custom-fit for businesses operating at scale.',
    image: 'services/business-systems-v01.webp',
    imagePosition: '50% 50%',
    label: 'Digital Services',
    order: 6,
    preview: 'Service + Scale',
    sections: [
      { body: 'Checkout that just works. Fast, reliable point-of-sale systems built to keep your business moving, one sale at a time.', title: 'POS Systems' },
      { body: 'Every call matters. We build systems that help your team respond faster, stay organized, and keep customers happy.', title: 'Customer Service Call Center Solutions' },
      { body: 'People are the heart of your business. We simplify hiring, payroll, and everyday HR, so your team can focus on people, not paperwork.', title: 'HRM Solutions' },
      { body: 'Big vision, solid foundation. Custom systems built to scale with you as your business grows.', title: 'Enterprise Solutions' },
    ],
    slug: 'business-systems',
    summary: 'We build the digital infrastructure behind the customer experience. POS, call centre, HR and enterprise systems are designed to work together, giving your business one connected foundation for digital workability.',
    tagline: 'Service + Scale',
  },
  {
    accent: '#8d33ff',
    cardHeadline: 'The idea. The room. The moment.',
    detailDescription: 'Events & Experiences covers everything from corporate functions and weddings to private celebrations and fully custom productions, handling concept through execution. Corporate events span conferences, seminars, AGMs, award ceremonies, retreats and gala dinners. Weddings can run from concept and planning through coordination and destination celebrations. Private and social events include birthdays, anniversaries, themed and surprise events, alongside larger community, cultural and festival experiences. When nothing fits a category, custom solutions cover event strategy, staging, AV production, entertainment booking, logistics and post-event reporting.',
    image: 'services/events-experiences-v01.webp',
    imagePosition: '50% 50%',
    label: 'Events & Experiences',
    order: 7,
    preview: 'Concept + Production',
    sections: [
      {
        body: 'Work events don’t always have to feel like work.\n\nFrom conferences and AGMs to award nights, team days, retreats and celebrations, we bring the whole thing together—the idea, the space, the people, the production and all the little details in between.\n\nWhatever gets your team, partners or people in the same room, we make it worth showing up for.',
        items: [
          { title: 'Conferences' },
          { title: 'Seminars & Workshops' },
          { title: 'Annual General Meetings (AGMs)' },
          { title: 'Award Ceremonies' },
          { title: 'Corporate Celebrations' },
          { title: 'Dealer & Partner Events' },
          { title: 'Family Days' },
          { title: 'Team Building' },
          { title: 'Retreats' },
          { title: 'Gala Dinners' },
        ],
        title: 'Corporate Events',
      },
      { body: 'Birthdays, anniversaries, engagements, surprise parties or just a good reason to get everyone together—each one can be as simple, loud, themed or completely unexpected as you want it to be.', title: 'Private Events' },
      { body: 'People show up for what they’re into.\n\nMusic, culture, sport, a cause, a community or simply meeting new people—social events can take many forms. The idea, programming, space, entertainment, production and everything around it are built to give people a reason to come, stay and be part of it.', title: 'Social Events' },
      { body: 'Your wedding should feel like you, not like every other wedding.\n\nFrom the first idea to the day itself, every detail comes together around your story—the concept, venue, décor, invites, entertainment, photography, film and everything happening behind the scenes.\n\nYour people. Your kind of celebration. Done your way.\n\nWhatever brings the crowd together, let’s make something out of it.', title: 'Weddings' },
      { body: 'Not every event fits into a category—and it doesn’t have to.\n\nCome with a full brief, half an idea or something that hasn’t been done before. Strategy, creative, planning, production, tech, talent, content and everything in between can be built around what the event actually needs.\n\nNo fixed formula. Just the right pieces, put together for the right reason.', title: 'Custom Event Solutions' },
    ],
    slug: 'events-experiences',
    summary: 'We build events the same way we build brands—concept first, then everything needed to bring it into a room. Corporate, wedding, private and custom productions stay tied to one creative direction, from first plan to the last guest out the door.',
    tagline: 'Concept + Production',
  },
  {
    accent: '#00aee8',
    cardHeadline: 'Trained to think. Built to act.',
    detailDescription: 'Agentic Biz Systems covers AI that actually works inside a business: autonomous AI agents and agentic workflows that automate multi-step processes end to end. Automation solutions take repetitive work off a team’s plate, while integration services connect AI cleanly into existing systems. Everything is built to support people’s work rather than replace it.',
    image: 'services/agentic-systems-v01.webp',
    imagePosition: '50% 50%',
    label: 'Agentic Biz Systems',
    order: 8,
    preview: 'Agents + Automation',
    sections: [
      { body: 'Work that happens on its own. We build AI agents that think, decide, and act, handling tasks without needing someone to babysit every step.', title: 'Autonomous AI Agents' },
      { body: 'Your processes, running themselves. We connect AI agents into your everyday workflows so tasks move forward automatically, from start to finish.', title: 'Agentic Workflows' },
      { body: 'Fewer repetitive tasks, more real work. We automate the busywork with AI, so your team can spend time on what actually moves the needle.', title: 'AI Automation Solutions' },
      { body: 'AI that fits right in. We plug intelligent tools into the systems you already use, no rip-and-replace, just smarter versions of what you have.', title: 'AI Integration Services' },
      { body: 'An extra set of hands that never clocks out. We pair your team with AI agents that handle the routine work, so your people can focus on the bigger picture.', title: 'Agentic Employee Augmentation' },
    ],
    slug: 'agentic-systems',
    summary: 'We design AI systems that do real work inside your business, not just answer questions. Agents, automation and integration are built as one connected layer, so the technology plugs into how your team already operates.',
    tagline: 'Agents + Automation',
  },
]
